baseicon := '../icon_512x512.png'
resdir := 'src/main/res'

generate-icons:
    mkdir -p {{resdir}}/drawable-nodpi
    magick {{baseicon}} \
        -resize 230x230 \
        -background none \
        -gravity center \
        -extent 432x432 \
        -strip \
        -define png:exclude-chunks=date,time \
        {{resdir}}/drawable-nodpi/icon.png
