# configuration is either "Debug" or "Release"
[macos]
build configuration:
    xcodebuild -configuration {{configuration}}
[macos]
run configuration:
    ./build/{{configuration}}/mpclipboard.app/Contents/MacOS/mpclipboard

[macos]
dev:
    cd ../generic-client && cargo build
    @just build Debug
    @just run Debug

[macos]
release:
    cd ../generic-client && cargo build --release
    @just build Release

    cd build/Release && \
        rm -rf dmg-root mpclipboard.dmg && \
        mkdir -p dmg-root && \
        cp -R mpclipboard.app dmg-root/ && \
        ln -s /Applications dmg-root/Applications && \
        hdiutil create -volname mpclipboard -srcfolder dmg-root -ov -format UDZO mpclipboard.dmg

    mv build/Release/mpclipboard.dmg ..

clean:
    rm -rf build
    rm -f mpclipboard.app.zip

upload version ref="master":
    gh workflow run release-macos --ref {{ref}} -f version={{version}}

baseicon := 'icon_512x512.png'

generate-icon name rgb:
    #!/usr/bin/env bash
    rm -rf mpclipboard/Assets.xcassets/{{name}}.imageset
    mkdir -p mpclipboard/Assets.xcassets/{{name}}.imageset

    variant() {
        local density=$1
        local size=$2
        local filename=$3
        magick {{baseicon}} \
            -density $density \
            -resize $size \
            -alpha set \
            -channel rgba \
            -fill "{{rgb}}" \
            -colorize 100% \
            mpclipboard/Assets.xcassets/{{name}}.imageset/$filename
    }

    variant 72  24x24 {{name}}.png
    variant 144 48x48 {{name}}@2x.png
    variant 216 72x72 {{name}}@3x.png

    cat > mpclipboard/Assets.xcassets/{{name}}.imageset/Contents.json <<EOF
        {
        "images": [
            { "filename": "{{name}}.png",    "idiom": "universal", "scale": "1x" },
            { "filename": "{{name}}@2x.png", "idiom": "universal", "scale": "2x" },
            { "filename": "{{name}}@3x.png", "idiom": "universal", "scale": "3x" }
        ],
        "info": { "version": 1, "author": "xcode" }
        }
    EOF

icons:
    @just generate-icon green "rgb(23, 199, 23)"
    @just generate-icon red "rgb(195, 40, 40)"
    @just generate-icon yellow "rgb(236, 223, 41)"
