# configuration is either "Debug" or "Release"
[macos]
build configuration:
    xcodebuild -configuration {{configuration}}
[macos]
run configuration:
    ./build/{{configuration}}/mpclipboard.app/Contents/MacOS/mpclipboard

[macos]
dev:
    cd ../generic-client && cargo build
    @just build Debug
    @just run Debug

[macos]
release:
    cd ../generic-client && cargo build --release
    @just build Release

    cd build/Release && \
        rm -rf dmg-root mpclipboard.dmg && \
        mkdir -p dmg-root && \
        cp -R mpclipboard.app dmg-root/ && \
        ln -s /Applications dmg-root/Applications && \
        hdiutil create -volname mpclipboard -srcfolder dmg-root -ov -format UDZO mpclipboard.dmg

    mv build/Release/mpclipboard.dmg ..

clean:
    rm -rf build
    rm -f mpclipboard.app.zip

upload version ref="master":
    gh workflow run release-macos --ref {{ref}} -f version={{version}}

baseicon := 'icon_512x512.png'
assetsdir := 'mpclipboard/Assets.xcassets'

generate-imageset-variant rgb density size outpath:
    magick {{baseicon}} \
        -density {{density}} \
        -resize {{size}} \
        -alpha set \
        -channel rgba \
        -fill "{{rgb}}" \
        -colorize 100% \
        {{outpath}}

generate-imageset name rgb:
    mkdir -p {{assetsdir}}/{{name}}.imageset

    @just generate-imageset-variant "{{rgb}}" 72  24x24 {{assetsdir}}/{{name}}.imageset/{{name}}.png
    @just generate-imageset-variant "{{rgb}}" 144 48x48 {{assetsdir}}/{{name}}.imageset/{{name}}@2x.png
    @just generate-imageset-variant "{{rgb}}" 216 72x72 {{assetsdir}}/{{name}}.imageset/{{name}}@3x.png

generate-iconset rgb:
    magick {{baseicon}} \
        -resize 32x32 \
        -alpha set \
        -channel rgba \
        -fill "{{rgb}}" \
        -colorize 100% \
        {{assetsdir}}/AppIcon.appiconset/icon-32x32.png

generate-all-resources:
    @just generate-imageset green  "rgb(23, 199, 23)"
    @just generate-imageset red    "rgb(195, 40, 40)"
    @just generate-imageset yellow "rgb(236, 223, 41)"

    @just generate-iconset "rgb(55, 54, 46)"
