dev:
    RUST_LOG=debug cargo run

now := `date +%s`

build-deb-package:
    cargo build --target=x86_64-unknown-linux-musl --release

    strip target/x86_64-unknown-linux-musl/release/mpclipboard-server
    cargo deb --deb-revision="{{now}}" -p mpclipboard-server --target=x86_64-unknown-linux-musl

container-build version:
    docker build -t ghcr.io/iliabylich/mpclipboard:{{version}} .

container-push version:
    docker push ghcr.io/iliabylich/mpclipboard:{{version}}

container-mark-latest version:
    docker tag ghcr.io/iliabylich/mpclipboard:{{version}} ghcr.io/iliabylich/mpclipboard:latest
    docker push ghcr.io/iliabylich/mpclipboard:latest

check:
    cargo check
