lib := '../generic-client/target/debug/libmpclipboard_generic_client.a'

dev-macos:
    cd ../generic-client && cargo build
    clang -fuse-ld=lld poll-cli.c {{lib}} -framework Security -framework CoreFoundation -o poll-cli
    RUST_LOG=info ./poll-cli

dev-linux:
    cd ../generic-client && cargo build
    clang -fuse-ld=lld poll-cli.c {{lib}} -o poll-cli
    RUST_LOG=info ./poll-cli
