cbindgen:
    cbindgen --output bindings.h

ws := 'ws://127.0.0.1:3000'
secret := 'sekret'

dev number:
    RUST_LOG=info cargo run --example cli -- {{ws}} {{secret}} client-{{number}} hello-from-client-{{number}}

valgrind:
    cargo build --example cli
    valgrind --leak-check=full target/debug/examples/cli

build:
    cargo build

release-android out:
    cargo ndk -t arm64-v8a build --release
    mv target/aarch64-linux-android/release/libmpclipboard_generic_client.a {{out}}
