name: CI

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    name: on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-latest
          - os: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v3
      - run: just ci
