name: release-macos

on:
  workflow_dispatch:
    inputs:
      version:
        description: release version in MAJOR.MINOR.PATCH version
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: extractions/setup-just@v3

      - run: find /Applications -name "Xcode*.app" -type d
      - run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
      - run: just macos::release
      - run: cp mpclipboard.dmg mpclipboard_${{ inputs.version }}.dmg

      - uses: mknejp/delete-release-assets@v1
        with:
          tag: latest
          assets: mpclipboard_*.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
          fail-if-no-assets: false
          fail-if-no-release: false

      - name: release (for version)
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true
          tag: server-v${{ inputs.version }}
          artifacts: mpclipboard_${{ inputs.version }}.dmg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: release (latest)
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          tag: latest
          artifacts: mpclipboard_${{ inputs.version }}.dmg
          token: ${{ secrets.GITHUB_TOKEN }}
