name: release-server

on:
  workflow_dispatch:
    inputs:
      version:
        description: release version in MAJOR.MINOR.PATCH version
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  release-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt update && sudo apt install musl musl-dev

      - uses: dtolnay/rust-toolchain@stable
        with: { targets: x86_64-unknown-linux-musl }

      - uses: extractions/setup-just@v3

      - uses: taiki-e/install-action@v2
        with: { tool: cargo-deb }

      - run: just server::release ${{ inputs.version }} $PWD/mpclipboard-server_${{ inputs.version }}.deb

      - uses: ./.github/actions/release
        with:
          filename: mpclipboard-server_${{ inputs.version }}.deb
          own-release-name: server-v${{ inputs.version }}
          previous-files-pattern: mpclipboard-server_*.deb
          token: ${{ secrets.GITHUB_TOKEN }}
